name: test_prj
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.3
  gap: ^1.2.0
  lipsum: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.0

flutter:
  uses-material-design: false

  assets:
    - assets/icons/close.png
